### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by tirumaraiselvan** [operator-framework/helm-app-operator-kit#11]
I am just trying to run this project from scratch.

I get the following error

```
kubectl create -f example-app-operator.v0.0.1.clusterserviceversion.yaml
error: unable to recognize "example-app-operator.v0.0.1.clusterserviceversion.yaml": no matches for kind "ClusterServiceVersion-v1" in version "app.coreos.com/v1alpha1"
```

Clearly, I do not have the Kind or the APIgroup? What are these? How do I install them

**Comment by 45cali** [comment]
I am getting the same issue

**Comment by alecmerdler** [comment]
I believe you are using an older version of the source code. Please try pulling the latest commits from `master` or re-cloning the repository.
