### ISSUE TITLE
Provide CRD object example

### ISSUE THREAD

**Issue by johnmarcou** [operator-framework/helm-app-operator-kit#13]
Hi,

Thank you for this project.

Can you provide in the documentation an example of on CRD definition to instance the Helm chart?
How the "final user" create a new `helm release`? How to provides the `release name`, the namespace, the `values`?

Thank you.

**Comment by alecmerdler** [comment]
We are in the process of rewriting this project to provide a better UX, which should be merged within the next couple days. You can view the [progress here](https://github.com/operator-framework/helm-app-operator-kit/pull/12). I think the new implementation will address your issue. Thanks!
