### ISSUE TITLE
"chart metadata (Chart.yaml) missing" when deploying custom resource

### ISSUE THREAD

**Issue by marekcbj** [operator-framework/helm-app-operator-kit#40]
Hi,

I deployed OLM to my cluster and Tomcat Operator from 'examples' (https://github.com/operator-framework/helm-app-operator-kit/tree/master/examples/tomcat-operator) . They are both up & running and Tomcat Operator is starting with following logs 

```
time="2018-09-18T10:23:09Z" level=info msg="Go Version: go1.10.4"
time="2018-09-18T10:23:09Z" level=info msg="Go OS/Arch: linux/amd64"
time="2018-09-18T10:23:09Z" level=info msg="operator-sdk Version: 0.0.5+git"
time="2018-09-18T10:23:09Z" level=info msg="Watching apache.org/v1alpha1, Tomcat, default, 5"
```

When I try to create new Tomcat resource with `kubectl create -f cr.yaml` , where `cr.yaml` is : 
```
apiVersion: apache.org/v1alpha1
kind: Tomcat
metadata:
  name: example-app
spec:
  replicaCount: 2
```

then I get following error in Tomcat Operator logs : 

```
time="2018-09-18T10:24:00Z" level=info msg="processing default/example-app"
time="2018-09-18T10:24:00Z" level=info msg="using values: replicaCount: 2\n"
time="2018-09-18T10:24:00Z" level=error msg="chart metadata (Chart.yaml) missing"
time="2018-09-18T10:24:00Z" level=error msg="error syncing key (default/example-app): chart metadata (Chart.yaml) missing"
```

I SSH'ed to Tomcat Operator Pod and I see tomcat helm chart under `/chart` directory and it contains `Chart.yaml`

**Comment by marekcbj** [comment]
Ok, I've found where the issue is . 

I'm creating operator image with using `.tgz` packaged helm chart : 
`docker build --build-arg HELM_CHART=tomcat-0.1.0.tgz --build-arg API_VERSION=apache.org/v1alpha1 --build-arg KIND=Tomcat -t <our_dtr_url>/tomcat-operator .`

Docker image build with this command has helm chart under `/charts/tomcat` , but in `Dockerfile` we are setting : `ENV HELM_CHART /chart` which is causing error. When I overridden this value with `ENV HELM_CHART /chart/tomcat` operator worked !

**Comment by joelanford** [comment]
Hi @marekcbj,

It sounds like you've got this figured out, but I wanted to point out that we updated the tomcat-operator example and README, and things may work a little bit differently now.

See #58 for details.

I'm going to close this for now, but if you're still having problems, feel free to reach back out.
