### ISSUE TITLE
Operator only sets status when the reconciler succeeds.

### ISSUE THREAD

**Issue by joelanford** [operator-framework/helm-app-operator-kit#59]
Right now, when a failure occurs in the Helm reconciler, no status updates are made to the resource, so consumers of these resources don't have great visibility when things go wrong. Currently the only way to see failures is by inspecting the operator logs.

We should update the operator to correctly set status at various points of reconciliation, not just on success

**Comment by hasbro17** [comment]
We could define a condition for whether a release is reconciled/installed(true, false, unknown) with the reason.
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties
Or turn that into a known field in status.

**Comment by joelanford** [comment]
Yeah I was reading up on conventions for `status` and I'm thinking the Helm status is due for an overhaul.

I think we need to be able to convey the following states:

Success (steady-state):
* "Deployed", with the deployed release
  * This would cover successes for install, update, and reconcile

Failure:
* "InstallFailed", with the failed release and a reason
* "UpdateFailed", with the deployed release, failed release, and a reason
* "ReconcileFailed", with the deployed release and a reason

Maybe we put "Deployed" and "DeployedRelease" as fields at the top-level status and then have a condition for the failures with a FailedRelease field in that condition?

**Comment by joelanford** [comment]
@hasbro17 I was about to submit a PR for this when I found the following discussions:
* https://github.com/kubernetes/kubernetes/issues/50798
* https://github.com/kubernetes/kubernetes/issues/7856#issuecomment-323196033

The doc you linked (https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties) was last updated before the above discussions happened, and nothing concrete seems to have been decided otherwise. In the absence of a clearly defined convention, I think I lean towards continuing with conditions as it seems to fit the Helm operator use case fairly well.

Thoughts?

**Comment by hasbro17** [comment]
Yep we can proceed with conditions. We can't go back to Phases and there doesn't seem to be an alternative convention to conditions yet(the issue on removing conditions is frozen https://github.com/kubernetes/kubernetes/issues/7856#issuecomment-356191423). 
The latest upstream proposals are still using conditions as well.
https://github.com/kubernetes/community/pull/2524/files#diff-61b3bf8a9689fb1a602ce6906cab8c4aR209

**Comment by joelanford** [comment]
The Helm operator has been integrated into operator-sdk. This issue was solved there by https://github.com/operator-framework/operator-sdk/pull/814
