### ISSUE TITLE
seperate chart data from generic operator

### ISSUE THREAD

**Issue by kfox1111** [operator-framework/helm-app-operator-kit#77]
I've been working on a driver that uses a data container as a volume. This would allow:
FROM scratch
ADD chart.tar.gz /chart

and a generic prebuilt helm-app-operator container to be used together, decoupling the cpu architecture specific operator container from the noarch chart container.

See: https://github.com/kubernetes-csi/drivers/issues/85
for details. The main issue left is getting inline pod support for ephemeral pods into kubernetes.
https://github.com/kubernetes/kubernetes/pull/68232

This would require a bit of support from the csv though I think. Are you interested in this use case?

**Comment by kfox1111** [comment]
Would just need some way to specify the extra volume for the data I think. There is a git volume driver already too, so you could probably support both use cases with the one extension to the CSV.

**Comment by joelanford** [comment]
I don't know for sure, but it looks like the entire deployment spec can be defined in the CSV, which should work with volumes and volumeMounts. Have you tried it?

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#operator-install
